version: '3'

services:

  myWordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: myMySQL:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress-pw
    volumes:
      - ./wordpress/code:/code
      - ./wordpress/html:/var/www/html
    depends_on:
      - myMySQL
    
  myMySQL:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress-pw
      MYSQL_DATABASE: wordpress
    volumes:
      - ./wordpress/pg-data:/var/lib/postgresql/data

volumes:
  pg-data: