version: '3.1'

services:

  node-dev:
    image: custom-node-alpine
    build: .
    
    working_dir: /home/node/app
    ports: 
      - 80:3000
    volumes:
      - ./:/home/node/app
    command: "bash"