version: '3'

services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    deploy:
      replicas: 2
      restart_policy: 
        condition: on-failure
    ports: 
      - 80:80
    networks:
      - frontend-network

  redis:
    image: redis:3.2
    networks: 
      - frontend-network

  db:
    image: postgres:9.4
    networks:
      - backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  result:
    image: dockersamples/examplevotingapp_result:before
    networks:
      - backend-network
    ports:
      - 5001:80

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend-network
      - backend-network
    
volumes:
  postgres-data:

networks:
    frontend-network:
      driver: overlay
    backend-network:
      driver: overlay